# steps:
# - name: node
#   entrypoint: npm
#   args: ['install']
# - name: node
#   entrypoint: npm
#   args: ['run', 'start']
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['test']
- name: node
  entrypoint: npm
  args: ['run', 'build']
