steps:
# - name: node
#   entrypoint: npm
#   args: ['install']
# - name: node
#   entrypoint: npm
#   args: ['run', 'start']
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
steps:
- name: 'gcr.io/cloud-builders/npm'  
  args: ['install']
- name: "gcr.io/cloud-builders/gcloud"  
  args: ["app", "deploy"]
  timeout: "1600s"
