# steps:
# - name: node
#   entrypoint: npm
#   args: ['install']
# - name: node
#   entrypoint: npm
#   args: ['run', 'start']
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]

# steps:
# - name: node
#   entrypoint: npm
#   args: ['install']
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']

steps:
- name: node:14.17.6
  entrypoint: npm
  args: ["install"]
- name: node:14.17.6
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'TYPE=${_TYPE}'
    - 'PROJECT_ID=${_PROJECT_ID}'
    - 'PRIVATE_KEY_ID=${_PRIVATE_KEY_ID}'
    - 'PRIVATE_KEY=${_PRIVATE_KEY}'
    - 'CLIENT_EMAIL=${_CLIENT_EMAIL}'
    - 'CLIENT_ID=${_CLIENT_ID}'
    - 'AUTH_URI=${_AUTH_URI}'
    - 'TOKEN_URI=${_TOKEN_URI}'
    - 'AUTH_PROVIDER_CERT_URL=${_AUTH_PROVIDER_CERT_URL}'
    - 'CLIENT_CERT_URL=${_CLIENT_CERT_URL}'
    - 'DB_CONNECTION=${_DB_CONNECTION}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
